name: media_probe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_route: ^7.7.1
  dartz: ^0.10.1
  dio: ^5.3.0
  dio_smart_retry: ^5.0.0
  equatable: ^2.0.5
  extended_image: ^8.0.2
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.19.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  intl: ^0.18.1
  json_serializable: ^6.7.1
  sqflite: ^2.2.8+4

dev_dependencies:  
  auto_route_generator: ^7.2.0
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.4.4
  json_annotation: ^4.8.1
  mockito: ^5.4.2
  mocktail: ^0.3.0
  pretty_dio_logger: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.development
    - assets/images/
    - assets/icons/
    - assets/colors/


flutter_gen:
  output: lib/src/config/gen/
  inputs:
    - assets/images/
    - assets/icons/
    - assets/colors/
  
  integrations:
    flutter_svg: true

  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors/colors.xml


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21